import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <meta charSet="UTF-8" />
        <link rel="icon" type="image/png" href="/nimbus-icon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Nimbus Data | Varredura e captura de dados de empresas em segundos!</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
